### ISSUE TITLE
About the rcom module

### ISSUE THREAD

**Issue by hashiTechRide** [RollMan/LtSRcon#1]
I am trying to write a script with reference to this repository now.
However, it stops with the following error.
"ImportError: No module named rcon"

Where can I get the rcom module?

Thank you

**Comment by RollMan** [comment]
Hi.

I assume that you already tryed to install `frostbite-rcon-utils` by `pip install frostbite-rcon-utils`.

The dependence `frostbite-rcon-utils` looks like be upgraded. It is not compatible with this script. So you have to use the older version of `frostbite-rcon-utils`. I checked its source code and v1.0.0 looks like compatible. Try following.
- `git clone https://github.com/edvinerikson/frostbite-rcon-utils-python`
- `cd frostbite-rcon-utils-python`
- `git checkout v1.0.0`
- `python setup.py install`

Perhaps you have to delete the existing one by `pip uninstall frostbite-rcon-utils` or something.

I no loger have the game server. I cannot verify it works completely. But the way removed "ImportError: No module named rcon" and it got `Invalid server address or port number.`

**Comment by hashiTechRide** [comment]
Hi.

I was able to solve the problem of rcon module.
Thank you for your courteous reply.

**Comment by RollMan** [comment]
Thank you for your reporting. I modified the README. 12f9c3203ceafa4c29c8814d143a3d8244aaac85
